#!/bin/sh

if [ $1 = "off" ]
then
echo "Shutdown screen service"
sudo sh -c "echo 508 > /sys/class/gpio/export"
sudo sh -c "echo 'out' > /sys/class/gpio/gpio508/direction"
sudo sh -c "echo '0' > /sys/class/gpio/gpio508/value"

elif [ $1 = "on" ]
then
echo "Turning on Screen, and re-setting framebuffer"
sudo sh -c "echo 508 > /sys/class/gpio/export"
sudo sh -c "echo 'out' > /sys/class/gpio/gpio508/direction"
sudo sh -c "echo '1' > /sys/class/gpio/gpio508/value"

else
echo "No valid command given, try on or off"
fi